### ISSUE TITLE
Markdown not working in Edit Talk Proposal page

### ISSUE THREAD

**Issue by Mariatta** [djangocon/2016.djangocon.us#87]
This is from Edit Talk Proposal page, it says we can edit with markdown.
So I entered some markdown text using the toolbars
<img width="515" alt="screen shot 2016-04-02 at 8 04 08 am" src="https://cloud.githubusercontent.com/assets/5844587/14227101/b0c9ce78-f8a9-11e5-8709-d8c9196cff2b.png">

This is the output once I pressed save.
<img width="1026" alt="screen shot 2016-04-02 at 8 04 21 am" src="https://cloud.githubusercontent.com/assets/5844587/14227100/b0c81826-f8a9-11e5-8a18-c8786833d1ac.png">

I'm using Chrome, if it matters?
Thanks.

**Comment by SaraDGore** [comment]
Not working in any browser (I tried Chrome, Firefox, and I.E.) Preview is also not working. Not even preserving paragraph spacings.

**Comment by jefftriplett** [comment]
We should be referencing `abstract_html` instead of `abstract` and `additional_notes_html` instead of `additional_notes ` in this template: https://github.com/djangocon/2016.djangocon.us/blob/development/djangocon/templates/symposion/proposals/_proposal_fields.html#L34#L37 base on Symposion's fields here: 

https://github.com/pinax/symposion/blob/master/symposion/proposals/models.py#L101

Since we are using PinaxCon's default templates (which have been ported to Bootstrap v4), we should submit a patch upstream (based on their templates not ours since they use Bootstrap v3) to this as well: https://github.com/pinax/PinaxCon/blob/master/pinaxcon/templates/symposion/proposals/_proposal_fields.html

**Comment by jefftriplett** [comment]
It's fixed for everything except for the "Special Requirements" which requires and upstream fix.

Thank you for reporting the issue @Mariatta!

**Comment by Mariatta** [comment]
Thank you!, @jefftriplett ! I can confirm that this is working now :)
