### ISSUE TITLE
What is a community sponsor?

### ISSUE THREAD

**Issue by pydanny** [djangocon/2016.djangocon.us#90]
Is it like a PyCon US sponsor? Something for Open Source projects to do? Or something else?

**Comment by jefftriplett** [comment]
Sorry to answer a question with a question, but are you requesting we have a community sponsor program? If so, please email your thoughts to hello@djangocon.us and we can get ideas and volunteers in the mix. Otherwise, we didn't have one last year because we were too small and no one asked about having one which doesn't mean we should not have one. Thanks for the question!

**Comment by pydanny** [comment]
The reason I asked about community sponsorship is that it exists in the drop-down list of potential sponsor types. Yet there is no description on the site as to what it means.

![screen shot 2016-04-05 at 1 46 06 pm](https://cloud.githubusercontent.com/assets/62857/14297653/d5708b1c-fb34-11e5-9042-22e405bdd499.png)

**Comment by pydanny** [comment]
Also, what is a "Technical" sponsorship?

**Comment by jefftriplett** [comment]
Thank you for pointing that out. `git grep` was not getting the job done which make sense now ;)

I checked with the team and the community sponsorship is carry-over from the initial fixtures we loaded into the database (or we mistyped them). It's really a diversity plan for the DSF, PSF, DEFNA, and other groups who donate to our diversity efforts.

We have a few catchall categories like our technical level for acknowledging sponsorship levels which don't fit into our metallic plans like hosting, cdn, saas, or other infrastructure.

Sorry for the confusion. Feel free to email me if you want to follow up or the sponsors@djangocon.us if you have ideas about what a "community sponsorship" *could* or *should* be.
